import { orangeP3, sandP3 } from '@radix-ui/colors';

export const theme = {
	'background-color': {
		'neutral': sandP3.sand1,
		'neutral-hover': sandP3.sand2,
		'neutral-pressed': sandP3.sand3,
		'neutral-disabled': sandP3.sand4,
		'neutral-selected': sandP3.sand5,
		'neutral-inverse': sandP3.sand12,
		'neutral-inverse-hover': sandP3.sand11,
		'neutral-inverse-pressed': sandP3.sand10,
		'neutral-inverse-disabled': sandP3.sand9,
		'accent': orangeP3.orange9,
		'accent-hover': orangeP3.orange8,
		'accent-pressed': orangeP3.orange7,
		'accent-disabled': orangeP3.orange6,
		'accent-selected': orangeP3.orange5,
		'accent-inverse': orangeP3.orange4,
		'accent-inverse-hover': orangeP3.orange3,
		'accent-inverse-pressed': orangeP3.orange2,
		'accent-inverse-disabled': orangeP3.orange1,
		// "success": success["9"],
		// "success-hover": success["8"],
		// "success-pressed": success["7"],
		// "warning": warning["9"],
		// "warning-hover": warning["8"],
		// "warning-pressed": warning["7"],
		// "error": error["9"],
		// "error-hover": error["8"],
		// "error-pressed": error["7"],
	},
	'border-color': {
		neutral: sandP3.sand6,
		accent: orangeP3.orange6,
		// "error": error[6],
		// "success": success[6],
		inverse: sandP3.sand12,
	},
	'text-color': {
		'neutral': sandP3.sand12,
		'neutral-muted': sandP3.sand11,
		'accent': orangeP3.orange10,
		'accent-muted': orangeP3.orange9,
		'neutral-inverse': sandP3.sand1,
		'neutral-inverse-muted': sandP3.sand2,
		'accent-inverse': orangeP3.orange1,
		'accent-inverse-muted': orangeP3.orange2,
		// "success": success[12],
		// "success-muted": success[11],
		// "success-inverse": success[1],
		// "success-inverse-muted": success[2],
		// "warning": warning[12],
		// "warning-muted": warning[11],
		// "warning-inverse": warning[1],
		// "warning-inverse-muted": warning[2],
		// "error": error[12],
		// "error-muted": error[11],
		// "error-inverse": error[1],
		// "error-inverse-muted": error[2],
	},
};
